INSERT INTO DEVICE(DEVICE_TYPE) VALUES ('AUTONOMOUS_CRAFT');


INSERT INTO data(DEVICE_ID, DATE, STATUS, LATITUDE, LATITUDE_DIRECTION,LONGITUDE, LONGITUDE_DIRECTION, HEADING, MAGNETIC_DEVIATION, DEVIATION_DIRECTION)
VALUES(1,current_date, 'A', 4.403, 'N', 51.21, 'E', 90.0, 0.0, 'E');

INSERT INTO DEVICE(DEVICE_TYPE) VALUES ('MOB_VICTIM');
INSERT INTO data(DEVICE_ID, DATE, STATUS, LATITUDE, LATITUDE_DIRECTION,LONGITUDE, LONGITUDE_DIRECTION, HEADING, MAGNETIC_DEVIATION, DEVIATION_DIRECTION)
VALUES(2,current_date, 'A', 4.403, 'N', 51.22, 'E', 90.0, 0.0, 'E');

SELECT * FROM DEVICE;
