INSERT INTO DEVICE(DEVICE_TYPE) VALUES ('MOB_VICTIM');


INSERT INTO DATA(DATA_ID, DEVICE_ID, DATE, STATUS, LATITUDE, LATITUDE_DIRECTION, LONGITUDE, LONGITUDE_DIRECTION, HEADING, MAGNETIC_DEVIATION, DEVIATION_DIRECTION)
VALUES(1,1,current_date, 'A', 40.1234, 'N', 70.1234, 'W', 90.0, 0.0, 'E');


SELECT * FROM DEVICE;
