DROP TABLE IF EXISTS DATA;
DROP TABLE IF EXISTS DEVICE;


CREATE TABLE IF NOT EXISTS DEVICE
(
    DEVICE_ID   INTEGER AUTO_INCREMENT PRIMARY KEY,
    DEVICE_TYPE VARCHAR(50)
);


CREATE TABLE IF NOT EXISTS DATA
(
    DATA_ID             INTEGER AUTO_INCREMENT PRIMARY KEY,
    DEVICE_ID           INTEGER,
    DATE                DATE,
    STATUS              VARCHAR(1),
    LATITUDE            DOUBLE,
    LATITUDE_DIRECTION  VARCHAR(3),
    LONGITUDE           DOUBLE,
    LONGITUDE_DIRECTION VARCHAR(3),
    HEADING             DOUBLE,
    MAGNETIC_DEVIATION  DOUBLE,
    DEVIATION_DIRECTION VARCHAR(3),
    CONSTRAINT DATA_DEVICE_DEVICE_ID_FK
    FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE (DEVICE_ID),
--     CONSTRAINT CHECK_DEVIATION_DIRECTION CHECK (DEVIATION_DIRECTION IN ('E', 'W', '')),
--     CONSTRAINT CHECK_LATITUDE_DIRECTION CHECK (LATITUDE_DIRECTION IN ('N', 'S', '')),
--     CONSTRAINT CHECK_LONGITUDE_DIRECTION CHECK (LONGITUDE_DIRECTION IN ('E', 'W', '')),
    CONSTRAINT CHECK_STATUS CHECK (STATUS IN ('A', 'V'))
);

