CREATE TABLE IF NOT EXISTS DEVICE
(
    DEVICE_ID   SERIAL NOT NULL,
    DEVICE_TYPE VARCHAR(50),
    CONSTRAINT DEVICE_PK PRIMARY KEY (DEVICE_ID)
);
CREATE TABLE IF NOT EXISTS DATA
(
    DATA_ID             SERIAL NOT NULL,
    DEVICE_ID           INT,
    DATE                DATE,
    STATUS              VARCHAR(1),
    LATITUDE            DOUBLE PRECISION,
    LATITUDE_DIRECTION  VARCHAR(1),
    LONGITUDE           DOUBLE PRECISION,
    LONGITUDE_DIRECTION VARCHAR(1),
    HEADING             DOUBLE PRECISION,
    MAGNETIC_DEVIATION  DOUBLE PRECISION,
    DEVIATION_DIRECTION VARCHAR(1),
    CONSTRAINT DATA_PK PRIMARY KEY (DATA_ID),
    CONSTRAINT DATA_DEVICE_DEVICE_ID_FK
        FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE,
    CONSTRAINT CHECK_DEVIATION_DIRECTION CHECK (DEVIATION_DIRECTION IN ('E', 'W')),
    CONSTRAINT CHECK_LATITUDE_DIRECTION CHECK (LATITUDE_DIRECTION IN ('N', 'S')),
    CONSTRAINT CHECK_LONGITUDE_DIRECTION CHECK (LONGITUDE_DIRECTION IN ('E', 'W')),
    CONSTRAINT CHECK_STATUS CHECK (STATUS IN ('A', 'V'))
);