version: '3.8'
services:
  db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_DB: 'hotelbooking'
      POSTGRES_USER: 'tayyab'
      POSTGRES_PASSWORD: 'tayyab'
    ports:
      - '5447:5432'
